name: math_lite
description: App de alfabetização matemática (PT/EN/ES) offline

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^16.3.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  drift: ^2.29.0
  drift_sqflite: ^2.0.1
  sqlite3_flutter_libs: ^0.5.40

  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  audioplayers: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.1
  drift_dev: ^2.29.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png

# Configuração do gerador de ícones
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
